events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    resolver kube-dns.kube-system.svc.cluster.local valid=10s;

    server {
        listen 80 default_server;
        server_name _;

        # UI do Cliente (Arquivos estáticos)
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ =404;
        }

        # Proxy para o Steering Server
        location /steering/ {
            proxy_pass https://steering-server.default.svc.cluster.local:30500/;
            proxy_ssl_verify off;
            proxy_set_header Host steering-server.default.svc.cluster.local;

            # CORS fix interno
            proxy_hide_header 'Access-Control-Allow-Origin';
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' '*' always;

            if ($request_method = 'OPTIONS') { return 204; }
        }

        # Proxy para Delivery Node 1
        location /node1/ {
            proxy_pass https://delivery-node-1.default.svc.cluster.local:443/;
            proxy_ssl_verify off;
            proxy_set_header Host delivery-node-1.default.svc.cluster.local;

            proxy_hide_header 'Access-Control-Allow-Origin';
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' '*' always;

            if ($request_method = 'OPTIONS') { return 204; }
        }

        # Proxy para Delivery Node 2
        location /node2/ {
            proxy_pass https://delivery-node-2.default.svc.cluster.local:443/;
            proxy_ssl_verify off;
            proxy_set_header Host delivery-node-2.default.svc.cluster.local;

            proxy_hide_header 'Access-Control-Allow-Origin';
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' '*' always;

            if ($request_method = 'OPTIONS') { return 204; }
        }

        # Proxy para Delivery Node 3
        location /node3/ {
            proxy_pass https://delivery-node-3.default.svc.cluster.local:443/;
            proxy_ssl_verify off;
            proxy_set_header Host delivery-node-3.default.svc.cluster.local;

            proxy_hide_header 'Access-Control-Allow-Origin';
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' '*' always;

            if ($request_method = 'OPTIONS') { return 204; }
        }
    }
}
